//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa4_Persistencia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class ConfiguracionDeClases : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfiguracionDeClases defaultInstance = ((ConfiguracionDeClases)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfiguracionDeClases())));
        
        public static ConfiguracionDeClases Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Capa4_Persistencia.FabricaPersistencia.FabricaConcretaSQLServer")]
        public string ParametroClaseFabricaDePersistencia {
            get {
                return ((string)(this["ParametroClaseFabricaDePersistencia"]));
            }
        }
    }
}
